server:
  port: ${port:8000}
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 2cbac16d-8042-4d95-93a7-e03e49f21913
        cluster-name: zwng
logging:
  level:
    root: info
    org.springframework: info